version: "3"
services:
  postgresql:
    image: postgres
    restart: always
    container_name: local-postgres
    environment:
      - "POSTGRES_USER=postgres"
      - "POSTGRES_DB=password_manager"
      - "POSTGRES_HOST_AUTH_METHOD=trust"
    ports:
      - 15432:5432